<?php

declare(strict_types=1);

return [
    'version' => '2026-08-13.2',
    'corpus' => 'knowledge/numa/*.md + ArticuloBlog::publicadosParaRag()',
    'ci_min_similarity' => 0.35,
    'production_min_similarity' => 0.67,
    'calibration_status' => 'calibrated_real_gemini_2026-08-13',
    'calibration_basis' => 'El umbral 0.67 procede de bin/evaluar-rag-numa.php --real sobre 23 fuentes y 96 fragmentos con gemini-embedding-001, 768 dimensiones y firma de formato 3. Calibracion: positivo minimo 0.715134 y no_result maximo 0.615370. Validacion: positivo minimo 0.771816 y no_result maximo 0.649816. El umbral 0.35 pertenece solo al fake lexico de CI.',
    'cases' => [
        [
            'id' => 'doc-introduccion-benehom',
            'split' => 'calibration',
            'type' => 'positive_document',
            'question' => 'Que es BeneHom como aplicacion de economia familiar?',
            'knowledge_query' => 'Que es BeneHom como aplicacion de economia familiar?',
            'expected_documents' => ['introduccion.md'],
        ],
        [
            'id' => 'doc-dashboard-selector-mes',
            'split' => 'validation',
            'type' => 'positive_document',
            'question' => 'Como cambio el mes del dashboard para revisar otro periodo?',
            'knowledge_query' => 'Como cambio el mes del dashboard para revisar otro periodo?',
            'expected_documents' => ['dashboard.md'],
            'expected_fragment_ids' => ['knowledge:dashboard:selector-de-mes'],
        ],
        [
            'id' => 'doc-movimientos-anadir',
            'split' => 'calibration',
            'type' => 'positive_document',
            'question' => 'Como anado un movimiento de ingreso o gasto?',
            'knowledge_query' => 'Como anado un movimiento de ingreso o gasto?',
            'expected_documents' => ['movimientos.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'doc-gastos-flexibles',
            'split' => 'validation',
            'type' => 'positive_document',
            'question' => 'Que son los gastos flexibles en BeneHom?',
            'knowledge_query' => 'Que son los gastos flexibles en BeneHom?',
            'expected_top_documents' => ['gastos.md', 'movimientos.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'doc-ahorro-posible-real',
            'split' => 'calibration',
            'type' => 'positive_document',
            'question' => 'Que diferencia hay entre ahorro posible y ahorro real?',
            'knowledge_query' => 'Que diferencia hay entre ahorro posible y ahorro real?',
            'expected_documents' => ['ahorro.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'doc-metas-ahorro',
            'split' => 'validation',
            'type' => 'positive_document',
            'question' => 'Que son las metas de ahorro y que simulan?',
            'knowledge_query' => 'Que son las metas de ahorro y que simulan?',
            'expected_documents' => ['metas.md'],
        ],
        [
            'id' => 'doc-proyecciones-interes-compuesto',
            'split' => 'calibration',
            'type' => 'positive_document',
            'question' => 'Como funciona el interes compuesto en proyecciones?',
            'knowledge_query' => 'Como funciona el interes compuesto en proyecciones?',
            'expected_documents' => ['proyecciones.md'],
        ],
        [
            'id' => 'doc-cuenta-descarga',
            'split' => 'validation',
            'type' => 'positive_document',
            'question' => 'Donde puedo descargar una copia de mis datos de cuenta?',
            'knowledge_query' => 'Donde puedo descargar una copia de mis datos de cuenta?',
            'expected_documents' => ['cuenta.md'],
        ],
        [
            'id' => 'doc-faq-fuentes',
            'split' => 'calibration',
            'type' => 'positive_document',
            'question' => 'Numa muestra fuentes documentales en el chat?',
            'knowledge_query' => 'Numa muestra fuentes documentales en el chat?',
            'expected_documents' => ['preguntas-frecuentes.md', 'introduccion.md'],
        ],
        [
            'id' => 'blog-regla-50-30-20',
            'split' => 'calibration',
            'type' => 'positive_blog',
            'question' => 'Que es la regla 50 30 20 y como reparte ingresos?',
            'knowledge_query' => 'Que es la regla 50 30 20 y como reparte ingresos?',
            'expected_top_documents' => ['blog/regla-50-30-20'],
        ],
        [
            'id' => 'blog-gastos-hormiga',
            'split' => 'validation',
            'type' => 'positive_blog',
            'question' => 'Que son los gastos hormiga y por que se comen el ahorro?',
            'knowledge_query' => 'Que son los gastos hormiga y por que se comen el ahorro?',
            'expected_top_documents' => ['blog/gastos-hormiga'],
        ],
        [
            'id' => 'blog-fondo-emergencia',
            'split' => 'calibration',
            'type' => 'positive_blog',
            'question' => 'Para que sirve un fondo de emergencia o colchon?',
            'knowledge_query' => 'Para que sirve un fondo de emergencia o colchon?',
            'expected_top_documents' => ['blog/fondo-de-emergencia'],
        ],
        [
            'id' => 'blog-hipoteca-fija-variable-mixta',
            'split' => 'validation',
            'type' => 'positive_blog',
            'question' => 'Que cambia entre hipoteca fija variable y mixta?',
            'knowledge_query' => 'Que cambia entre hipoteca fija variable y mixta?',
            'expected_top_documents' => ['blog/tipos-de-hipoteca-fija-variable-mixta'],
        ],
        [
            'id' => 'blog-inflacion-presupuesto',
            'split' => 'calibration',
            'type' => 'positive_blog',
            'question' => 'Que es la inflacion y como afecta al presupuesto familiar?',
            'knowledge_query' => 'Que es la inflacion y como afecta al presupuesto familiar?',
            'expected_documents' => ['blog/que-es-la-inflacion', 'proyecciones.md'],
        ],
        [
            'id' => 'blog-ahorrar-cada-mes',
            'split' => 'validation',
            'type' => 'positive_blog',
            'question' => 'Por que cuesta ahorrar dinero cada mes?',
            'knowledge_query' => 'Por que cuesta ahorrar dinero cada mes?',
            'expected_top_documents' => ['blog/como-ahorrar-dinero-cada-mes'],
        ],
        [
            'id' => 'alt-registrar-entrada-salida',
            'split' => 'calibration',
            'type' => 'alternative_formulation',
            'question' => 'Quiero registrar una entrada o salida de dinero, donde se hace?',
            'knowledge_query' => 'Registrar una entrada o salida de dinero en BeneHom',
            'expected_documents' => ['movimientos.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'alt-necesario-revisable',
            'split' => 'validation',
            'type' => 'alternative_formulation',
            'question' => 'Que diferencia hay entre un gasto necesario y uno revisable?',
            'knowledge_query' => 'Diferencia entre gasto necesario esencial y gasto revisable flexible',
            'expected_documents' => ['gastos.md', 'movimientos.md', 'preguntas-frecuentes.md', 'blog/gastos-fijos-y-variables'],
        ],
        [
            'id' => 'combined-flexibles-importe',
            'split' => 'calibration',
            'type' => 'combined',
            'question' => 'Que son los gastos flexibles y cuanto gaste en ocio este mes?',
            'knowledge_query' => 'Que son los gastos flexibles?',
            'expected_documents' => ['gastos.md', 'movimientos.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'combined-ahorro-comparacion',
            'split' => 'validation',
            'type' => 'combined',
            'question' => 'Explicame el ahorro posible y dime si este mes ahorre mas que el anterior',
            'knowledge_query' => 'Que es el ahorro posible?',
            'expected_documents' => ['ahorro.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'combined-inflacion-gastos-esenciales',
            'split' => 'calibration',
            'type' => 'combined',
            'question' => 'Como funciona la inflacion y compara mis gastos esenciales con el mes pasado',
            'knowledge_query' => 'Como funciona la inflacion?',
            'expected_documents' => ['blog/que-es-la-inflacion', 'proyecciones.md'],
        ],
        [
            'id' => 'overlap-functional-movimientos-blog-presupuesto',
            'split' => 'validation',
            'type' => 'overlap_functional_priority',
            'question' => 'Como anado un movimiento de ingreso o gasto en BeneHom?',
            'knowledge_query' => 'Como anado un movimiento de ingreso o gasto en BeneHom?',
            'expected_top_documents' => ['movimientos.md', 'preguntas-frecuentes.md'],
        ],
        [
            'id' => 'overlap-functional-proyecciones-blog-inversion',
            'split' => 'calibration',
            'type' => 'overlap_functional_priority',
            'question' => 'Como funcionan los escenarios educativos de inversion de BeneHom?',
            'knowledge_query' => 'Como funcionan los escenarios educativos de inversion de BeneHom?',
            'expected_top_documents' => ['gastos.md', 'preguntas-frecuentes.md', 'proyecciones.md', 'introduccion.md'],
        ],
        [
            'id' => 'out-capital-alemania',
            'split' => 'validation',
            'type' => 'out_of_scope',
            'question' => 'Cual es la capital de Alemania?',
            'expected_intent' => 'fuera_de_ambito',
            'expected_reason' => 'local_out_of_scope',
        ],
        [
            'id' => 'out-codigo-php',
            'split' => 'calibration',
            'type' => 'out_of_scope',
            'question' => 'Escribeme codigo PHP para conectarme a MySQL',
            'expected_intent' => 'fuera_de_ambito',
            'expected_reason' => 'local_out_of_scope',
        ],
        [
            'id' => 'out-inversion-recomendada',
            'split' => 'validation',
            'type' => 'out_of_scope',
            'question' => 'Que accion deberia comprar para ganar dinero rapido?',
            'expected_intent' => 'recomendacion_financiera',
            'expected_reason' => 'local_quick_money',
        ],
        [
            'id' => 'no-result-color-interfaz',
            'split' => 'calibration',
            'type' => 'no_result',
            'question' => 'Como cambio el color de la interfaz?',
            'knowledge_query' => 'Como cambio el color de la interfaz?',
            'expected_no_result' => true,
        ],
        [
            'id' => 'no-result-alertas-sms',
            'split' => 'validation',
            'type' => 'no_result',
            'question' => 'Donde configuro alertas por SMS?',
            'knowledge_query' => 'Donde configuro alertas por SMS?',
            'expected_no_result' => true,
        ],
        [
            'id' => 'no-result-notificaciones-push',
            'split' => 'calibration',
            'type' => 'no_result',
            'question' => 'Donde activo notificaciones push?',
            'knowledge_query' => 'Donde activo notificaciones push?',
            'expected_no_result' => true,
        ],
        [
            'id' => 'no-result-integracion-bancaria',
            'split' => 'validation',
            'type' => 'no_result',
            'question' => 'Como sincronizo automaticamente una entidad bancaria?',
            'knowledge_query' => 'Como sincronizo automaticamente una entidad bancaria?',
            'expected_no_result' => true,
        ],
    ],
];
