<?php

return [
    'linea_editorial' => [
        'proposito' => 'Cada artículo responde a una pregunta real sobre el dinero del hogar (la que la gente busca de verdad) con lenguaje cercano, y muestra cómo aplicarla en BeneHom como remate natural, no como argumento de venta.',
        'tono' => [
            'cercano',
            'claro',
            'calmado',
            'profesional sin rigidez',
            'aplicable a decisiones domésticas',
        ],
        'evitar' => [
            'tecnicismos innecesarios',
            'tono bancario',
            'alarmismo',
            'promesas de rentabilidad',
            'recomendaciones de productos concretos',
            'títulos centrados en vocabulario interno que nadie busca',
        ],
        'cierre' => 'El campo conexion sigue siendo obligatorio y enlaza el tema con una funcionalidad real (dashboard, metas, proyecciones o gráficos), pero como aplicación práctica al final del recorrido, no como reclamo.',
    ],
    'enfoque_captacion' => [
        'objetivo' => 'El blog es el principal activo SEO del producto: capta a quien aún no conoce BeneHom respondiendo a lo que busca y lo acerca a la herramienta.',
        'principio_puente' => 'El título usa el término que la gente teclea en un buscador; el vocabulario propio (ahorro posible, ahorro real, esencial, flexible) vive dentro del texto como marco que resuelve la pregunta, no en el titular.',
        'recorrido' => 'pregunta real (intención de búsqueda) → marco que la resuelve (concepto BeneHom) → aplicación práctica con la conexion.',
    ],
    'categorias_oficiales' => [
        'ahorro' => 'Ahorro',
        'gastos' => 'Gastos',
        'metas' => 'Metas',
        'proyecciones' => 'Proyecciones',
        'habitos' => 'Hábitos',
        'inflacion' => 'Inflación',
        'hipotecas' => 'Hipotecas',
        'conceptos_basicos' => 'Conceptos básicos',
        'activos_financieros' => 'Activos financieros',
    ],
    'estructura_articulo' => [
        'secciones' => 3,
        'parrafos_por_seccion' => 2,
        'lectura_min' => [
            'minimo' => 4,
            'maximo' => 6,
        ],
        'resumen' => 'Una frase que anticipe el aprendizaje práctico del artículo, usando el lenguaje de la consulta de búsqueda.',
        'enfoque' => 'Sección 1: plantea la pregunta tal como la vive y la busca el lector. Sección 2: la resuelve introduciendo el concepto BeneHom como marco. Sección 3: la aplica y remata con la conexion.',
        'campos_requeridos' => [
            'slug',
            'categoria',
            'titulo',
            'resumen',
            'intencion_busqueda',
            'fecha',
            'estado',
            'lectura_min',
            'destacado',
            'icono',
            'contenido',
            'conexion',
        ],
    ],
    'reenfoque_seo' => [
        'fecha' => '2026-06-13',
        'motivo' => 'Los artículos del Sprint 15 estaban escritos para explicar conceptos internos de BeneHom (contenido de retención), con títulos sobre vocabulario propio que nadie busca. Se reorientan a intención de búsqueda real (contenido de captación) sin perder voz, concepto ni conexion.',
        'titulos_reenfocados' => [
            'ahorro-posible-y-ahorro-real => cuanto-puedes-ahorrar-cada-mes',
            'gastos-esenciales-y-gastos-flexibles => gastos-fijos-y-variables',
            'metas-de-ahorro-realistas => metas-de-ahorro-como-cumplirlas',
            'interes-compuesto-explicado-para-tu-hogar => que-es-el-interes-compuesto',
            'pequenos-habitos-grandes-cifras => gastos-hormiga',
            'colchon-de-emergencia-antes-de-invertir => fondo-de-emergencia',
            'inflacion-y-presupuesto-del-hogar => que-es-la-inflacion',
            'hipotecas-cuota-y-decision-familiar => cuanta-hipoteca-puedes-pagar',
            'activos-financieros-basicos => como-empezar-a-invertir-desde-cero',
        ],
        'articulos_captacion_nuevos' => [
            'como-hacer-un-presupuesto-familiar (destacado)',
            'regla-50-30-20',
            'como-ahorrar-dinero-cada-mes',
            'vivir-por-debajo-de-tus-posibilidades',
        ],
        'nota' => 'Cambiar slugs y títulos ahora no rompe SEO: el blog aún redirige a login y no está indexado. Conviene aplicarlo antes del Sprint 16, que publica el blog y genera meta descriptions, Open Graph y sitemap a partir de titulo, resumen e intencion_busqueda.',
    ],
];
