<?php

declare(strict_types=1);

return [
    'home/index' => [
        'controller' => 'HomeController',
        'action' => 'index',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'auth/login' => [
        'controller' => 'AuthController',
        'action' => 'login',
        'methods' => ['GET', 'POST'],
        'public' => true,
        'response' => 'html',
    ],
    'auth/logout' => [
        'controller' => 'AuthController',
        'action' => 'logout',
        'methods' => ['GET'],
        'public' => false,
        'response' => 'html',
    ],
    'registro/registrarUsuario' => [
        'controller' => 'RegistroController',
        'action' => 'registrarUsuario',
        'methods' => ['GET', 'POST'],
        'public' => true,
        'response' => 'html',
    ],
    'password/mostrarFormularioOlvido' => [
        'controller' => 'PasswordController',
        'action' => 'mostrarFormularioOlvido',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'password/procesarFormularioOlvido' => [
        'controller' => 'PasswordController',
        'action' => 'procesarFormularioOlvido',
        'methods' => ['POST'],
        'public' => true,
        'response' => 'html',
    ],
    'password/reset' => [
        'controller' => 'PasswordController',
        'action' => 'reset',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'password/procesarReset' => [
        'controller' => 'PasswordController',
        'action' => 'procesarReset',
        'methods' => ['POST'],
        'public' => true,
        'response' => 'html',
    ],
    'verificacion/verificar' => [
        'controller' => 'VerificacionController',
        'action' => 'verificar',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'verificacion/mostrarFormularioReenvio' => [
        'controller' => 'VerificacionController',
        'action' => 'mostrarFormularioReenvio',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'verificacion/reenviar' => [
        'controller' => 'VerificacionController',
        'action' => 'reenviar',
        'methods' => ['POST'],
        'public' => true,
        'response' => 'html',
    ],
    'blog/index' => [
        'controller' => 'BlogController',
        'action' => 'index',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'blog/detalle' => [
        'controller' => 'BlogController',
        'action' => 'detalle',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'seo/sitemap' => [
        'controller' => 'SeoController',
        'action' => 'sitemap',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'legal/privacidad' => [
        'controller' => 'LegalController',
        'action' => 'privacidad',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'legal/terminos' => [
        'controller' => 'LegalController',
        'action' => 'terminos',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'legal/aviso' => [
        'controller' => 'LegalController',
        'action' => 'aviso',
        'methods' => ['GET'],
        'public' => true,
        'response' => 'html',
    ],
    'dashboard/index' => [
        'controller' => 'DashboardController',
        'action' => 'index',
        'methods' => ['GET'],
        'public' => false,
        'response' => 'html',
    ],
    'dashboard/importarMesAnteriorAjax' => [
        'controller' => 'DashboardController',
        'action' => 'importarMesAnteriorAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'graficos/estadoGeneral' => [
        'controller' => 'GraficosController',
        'action' => 'estadoGeneral',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'graficos/gastos6m' => [
        'controller' => 'GraficosController',
        'action' => 'gastos6m',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'graficos/ahorros6m' => [
        'controller' => 'GraficosController',
        'action' => 'ahorros6m',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'graficos/topCategorias' => [
        'controller' => 'GraficosController',
        'action' => 'topCategorias',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'ingreso/agregarAjax' => [
        'controller' => 'IngresoController',
        'action' => 'agregarAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'ingreso/eliminarAjax' => [
        'controller' => 'IngresoController',
        'action' => 'eliminarAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'ingreso/editarAjax' => [
        'controller' => 'IngresoController',
        'action' => 'editarAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'gasto/agregarGastoEsencialAjax' => [
        'controller' => 'GastoController',
        'action' => 'agregarGastoEsencialAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'gasto/eliminarGastoAjax' => [
        'controller' => 'GastoController',
        'action' => 'eliminarGastoAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'gasto/editarGastoAjax' => [
        'controller' => 'GastoController',
        'action' => 'editarGastoAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'gasto/agregarGastoFlexibleAjax' => [
        'controller' => 'GastoController',
        'action' => 'agregarGastoFlexibleAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'cuenta/index' => [
        'controller' => 'CuentaController',
        'action' => 'index',
        'methods' => ['GET'],
        'public' => false,
        'response' => 'html',
    ],
    'cuenta/cambiarPassword' => [
        'controller' => 'CuentaController',
        'action' => 'cambiarPassword',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'cuenta/eliminarCuenta' => [
        'controller' => 'CuentaController',
        'action' => 'eliminarCuenta',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'cuenta/exportarDatos' => [
        'controller' => 'CuentaController',
        'action' => 'exportarDatos',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/index' => [
        'controller' => 'ProyeccionesController',
        'action' => 'index',
        'methods' => ['GET'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/simularCategoriaAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'simularCategoriaAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/crearEscenarioInversion' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearEscenarioInversion',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/actualizarEscenarioInversionAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'actualizarEscenarioInversionAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarEscenarioInversion' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarEscenarioInversion',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/crearMetaAhorro' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearMetaAhorro',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/eliminarMetaAhorro' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarMetaAhorro',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/actualizarImporteMetaAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'actualizarImporteMetaAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/actualizarAhorroMensualAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'actualizarAhorroMensualAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/crearInflacionProyeccion' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearInflacionProyeccion',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/actualizarInflacionProyeccionAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'actualizarInflacionProyeccionAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarInflacionProyeccion' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarInflacionProyeccion',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/crearCalculadoraHipoteca' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearCalculadoraHipoteca',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/actualizarCalculadoraHipotecaAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'actualizarCalculadoraHipotecaAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarCalculadoraHipoteca' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarCalculadoraHipoteca',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'html',
    ],
    'proyecciones/crearMetaAhorroAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearMetaAhorroAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarMetaAhorroAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarMetaAhorroAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/crearEscenarioInversionAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearEscenarioInversionAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarEscenarioInversionAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarEscenarioInversionAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/crearInflacionProyeccionAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearInflacionProyeccionAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarInflacionProyeccionAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarInflacionProyeccionAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/crearCalculadoraHipotecaAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'crearCalculadoraHipotecaAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'proyecciones/eliminarCalculadoraHipotecaAjax' => [
        'controller' => 'ProyeccionesController',
        'action' => 'eliminarCalculadoraHipotecaAjax',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
    ],
    'numa/chat' => [
        'controller' => 'NumaController',
        'action' => 'chat',
        'methods' => ['POST'],
        'public' => false,
        'response' => 'json',
        'csrf' => false,
    ],
    'numa/status' => [
        'controller' => 'NumaController',
        'action' => 'status',
        'methods' => ['GET'],
        'public' => false,
        'response' => 'json',
    ],
];
